AWSTemplateFormatVersion: "2010-09-09"
Description: Root stack
Resources:
  sshKeyPair:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cf-bucket-template.s3.ap-southeast-1.amazonaws.com/key-pair/main.yaml
