AWSTemplateFormatVersion: "2010-09-09"
Description: VPC for Dev environment
Resources:
  devVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 172.16.0.0/16
      EnableDnsSupport: "true"
      EnableDnsHostnames: "true"
      Tags:
        - Key: Name
          Value: devopslite-dev-vpc
        - Key: Env
          Value: Dev
